#!/bin/sh

for test in `find test -name '*.args'`
do
    test_name=`basename $test .args`
    bin/smoke `cat $test` > test/$test_name.out
    status=$?
    if [ $status -ne 0 ]; then
        echo $status > test/$test_name.status
    fi
done
