name: smoke
version: 2.1.0
github: SamirTalwar/smoke
license: MIT
author: Samir Talwar
maintainer: samir@noodlesandwich.com
copyright: Samir Talwar

extra-source-files:
  - README.md

synopsis: An integration test framework for console applications.
category: Testing
description: Please see README.md

dependencies:
  - base >= 4.12 && < 5
  - aeson
  - containers
  - data-default
  - directory
  - exceptions
  - filepath
  - Glob
  - process
  - process-extras
  - tar
  - temporary
  - text
  - transformers
  - vector
  - yaml

library:
  source-dirs:
    - src
  exposed-modules:
    - Test.Smoke
    - Test.Smoke.Paths
  ghc-options:
    - -Wall
    - -Werror
  when:
    condition: os(windows)
    then:
      source-dirs:
        - src/windows
    else:
      source-dirs:
        - src/unix

executables:
  smoke:
    source-dirs:
      - app
    main: Test/Smoke/App/Main.hs
    dependencies:
      - smoke
      - ansi-terminal
      - Diff
      - mtl
      - optparse-applicative
      - temporary
    ghc-options:
      - -Wall
      - -Werror
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    when:
      condition: os(windows)
      then:
        source-dirs:
          - app/windows
      else:
        source-dirs:
          - app/unix
        dependencies:
          - unix

tests:
  smoke-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - smoke
      - hedgehog
      - hspec
      - hw-hspec-hedgehog

build-tools:
  - hindent
  - hlint

when:
  - condition: "!os(windows)"
    build-tools:
      - cabal2nix
